export const imagesPath = {
  gallery: require('./images/gallery.png'),
  camera: require('./images/camera.png'),
  download: require('./images/download.png'),
  share: require('./images/share.png'),
  backArrow: require('./images/arrow.png'),
  bg1: require('./images/chooseVideoBg/h1.jpg'),
  bg2: require('./images/chooseVideoBg/h2.jpg'),
  bg3: require('./images/chooseVideoBg/h3.jpg'),
  bg4: require('./images/chooseVideoBg/h4.jpg'),
  bg5: require('./images/chooseVideoBg/h5.jpg'),
  bg6: require('./images/chooseVideoBg/h6.jpg'),
  bg7: require('./images/chooseVideoBg/h7.jpg'),
  playButton: require('./images/play-button.png'),
  pauseButton: require('./images/video-pause-button.png'),
  close: require('./images/close.png'),
  tickMark: require('./images/check.png'),
  img1: require('./images/chooseImageBg/p1.jpg'),
  img2: require('./images/chooseImageBg/p2.jpg'),
  img3: require('./images/chooseImageBg/p3.jpg'),
  img4: require('./images/chooseImageBg/p4.jpg'),
  img5: require('./images/chooseImageBg/p5.jpg'),
  img6: require('./images/chooseImageBg/p6.jpg'),
}